# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.BUILD_PATH }}
      - name: Install and compile
        uses: appleboy/ssh-action@v0.1.4
        with: 
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd ~/github/dashboard_build/
            npm install
            npm run build
            cp -r ~/github/dashboard_build/dist/ /var/www/dashboard/
            rm -rf ~/github/dashboard_build/*
